/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';

/**
 *
 * @export
 * @interface AccountRegisterRequestDTO
 */
export interface AccountRegisterRequestDTO {
    /**
     *
     */
    account: Account;
    /**
     *
     */
    password: string;
}

/**
 * Check if a given object implements the AccountRegisterRequestDTO interface.
 */
export function instanceOfAccountRegisterRequestDTO(value: object): value is AccountRegisterRequestDTO {
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AccountRegisterRequestDTOFromJSON(json: any): AccountRegisterRequestDTO {
    return AccountRegisterRequestDTOFromJSONTyped(json, false);
}

export function AccountRegisterRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRegisterRequestDTO {
    if (json == null) {
        return json;
    }
    return {

        'account': AccountFromJSON(json['account']),
        'password': json['password'],
    };
}

export function AccountRegisterRequestDTOToJSON(json: any): AccountRegisterRequestDTO {
    return AccountRegisterRequestDTOToJSONTyped(json, false);
}

export function AccountRegisterRequestDTOToJSONTyped(value?: AccountRegisterRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'account': AccountToJSON(value['account']),
        'password': value['password'],
    };
}
