/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';
import type { Tokens } from './Tokens';
import {
    TokensFromJSON,
    TokensFromJSONTyped,
    TokensToJSON,
    TokensToJSONTyped,
} from './Tokens';

/**
 *
 * @export
 * @interface AccountLoginResponseDTO
 */
export interface AccountLoginResponseDTO {
    /**
     *
     */
    account?: Account;
    /**
     *
     */
    tokens?: Tokens;
}

/**
 * Check if a given object implements the AccountLoginResponseDTO interface.
 */
export function instanceOfAccountLoginResponseDTO(value: object): value is AccountLoginResponseDTO {
    return true;
}

export function AccountLoginResponseDTOFromJSON(json: any): AccountLoginResponseDTO {
    return AccountLoginResponseDTOFromJSONTyped(json, false);
}

export function AccountLoginResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountLoginResponseDTO {
    if (json == null) {
        return json;
    }
    return {

        'account': json['account'] == null ? undefined : AccountFromJSON(json['account']),
        'tokens': json['tokens'] == null ? undefined : TokensFromJSON(json['tokens']),
    };
}

export function AccountLoginResponseDTOToJSON(json: any): AccountLoginResponseDTO {
    return AccountLoginResponseDTOToJSONTyped(json, false);
}

export function AccountLoginResponseDTOToJSONTyped(value?: AccountLoginResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'account': AccountToJSON(value['account']),
        'tokens': TokensToJSON(value['tokens']),
    };
}
