/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';

/**
 *
 * @export
 * @interface AccountMeResponseDTO
 */
export interface AccountMeResponseDTO {
    /**
     *
     */
    account?: Account;
}

/**
 * Check if a given object implements the AccountMeResponseDTO interface.
 */
export function instanceOfAccountMeResponseDTO(value: object): value is AccountMeResponseDTO {
    return true;
}

export function AccountMeResponseDTOFromJSON(json: any): AccountMeResponseDTO {
    return AccountMeResponseDTOFromJSONTyped(json, false);
}

export function AccountMeResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountMeResponseDTO {
    if (json == null) {
        return json;
    }
    return {

        'account': json['account'] == null ? undefined : AccountFromJSON(json['account']),
    };
}

export function AccountMeResponseDTOToJSON(json: any): AccountMeResponseDTO {
    return AccountMeResponseDTOToJSONTyped(json, false);
}

export function AccountMeResponseDTOToJSONTyped(value?: AccountMeResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'account': AccountToJSON(value['account']),
    };
}
