/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tokens } from './Tokens';
import {
    TokensFromJSON,
    TokensFromJSONTyped,
    TokensToJSON,
    TokensToJSONTyped,
} from './Tokens';

/**
 *
 * @export
 * @interface AccountRefreshResponseDTO
 */
export interface AccountRefreshResponseDTO {
    /**
     *
     */
    tokens?: Tokens;
}

/**
 * Check if a given object implements the AccountRefreshResponseDTO interface.
 */
export function instanceOfAccountRefreshResponseDTO(value: object): value is AccountRefreshResponseDTO {
    return true;
}

export function AccountRefreshResponseDTOFromJSON(json: any): AccountRefreshResponseDTO {
    return AccountRefreshResponseDTOFromJSONTyped(json, false);
}

export function AccountRefreshResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRefreshResponseDTO {
    if (json == null) {
        return json;
    }
    return {

        'tokens': json['tokens'] == null ? undefined : TokensFromJSON(json['tokens']),
    };
}

export function AccountRefreshResponseDTOToJSON(json: any): AccountRefreshResponseDTO {
    return AccountRefreshResponseDTOToJSONTyped(json, false);
}

export function AccountRefreshResponseDTOToJSONTyped(value?: AccountRefreshResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'tokens': TokensToJSON(value['tokens']),
    };
}
