/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AccountForgotPasswordRequestDTO
 */
export interface AccountForgotPasswordRequestDTO {
    /**
     *
     */
    email: string;
}

/**
 * Check if a given object implements the AccountForgotPasswordRequestDTO interface.
 */
export function instanceOfAccountForgotPasswordRequestDTO(value: object): value is AccountForgotPasswordRequestDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AccountForgotPasswordRequestDTOFromJSON(json: any): AccountForgotPasswordRequestDTO {
    return AccountForgotPasswordRequestDTOFromJSONTyped(json, false);
}

export function AccountForgotPasswordRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountForgotPasswordRequestDTO {
    if (json == null) {
        return json;
    }
    return {

        'email': json['email'],
    };
}

export function AccountForgotPasswordRequestDTOToJSON(json: any): AccountForgotPasswordRequestDTO {
    return AccountForgotPasswordRequestDTOToJSONTyped(json, false);
}

export function AccountForgotPasswordRequestDTOToJSONTyped(value?: AccountForgotPasswordRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'email': value['email'],
    };
}
