/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AccountRefreshRequestDTO
 */
export interface AccountRefreshRequestDTO {
    /**
     *
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the AccountRefreshRequestDTO interface.
 */
export function instanceOfAccountRefreshRequestDTO(value: object): value is AccountRefreshRequestDTO {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function AccountRefreshRequestDTOFromJSON(json: any): AccountRefreshRequestDTO {
    return AccountRefreshRequestDTOFromJSONTyped(json, false);
}

export function AccountRefreshRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRefreshRequestDTO {
    if (json == null) {
        return json;
    }
    return {

        'refreshToken': json['refreshToken'],
    };
}

export function AccountRefreshRequestDTOToJSON(json: any): AccountRefreshRequestDTO {
    return AccountRefreshRequestDTOToJSONTyped(json, false);
}

export function AccountRefreshRequestDTOToJSONTyped(value?: AccountRefreshRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'refreshToken': value['refreshToken'],
    };
}
