/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';

/**
 *
 * @export
 * @interface AccountVerifyEmailResponseDTO
 */
export interface AccountVerifyEmailResponseDTO {
    /**
     *
     */
    account?: Account;
}

/**
 * Check if a given object implements the AccountVerifyEmailResponseDTO interface.
 */
export function instanceOfAccountVerifyEmailResponseDTO(value: object): value is AccountVerifyEmailResponseDTO {
    return true;
}

export function AccountVerifyEmailResponseDTOFromJSON(json: any): AccountVerifyEmailResponseDTO {
    return AccountVerifyEmailResponseDTOFromJSONTyped(json, false);
}

export function AccountVerifyEmailResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountVerifyEmailResponseDTO {
    if (json == null) {
        return json;
    }
    return {

        'account': json['account'] == null ? undefined : AccountFromJSON(json['account']),
    };
}

export function AccountVerifyEmailResponseDTOToJSON(json: any): AccountVerifyEmailResponseDTO {
    return AccountVerifyEmailResponseDTOToJSONTyped(json, false);
}

export function AccountVerifyEmailResponseDTOToJSONTyped(value?: AccountVerifyEmailResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'account': AccountToJSON(value['account']),
    };
}
