/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AccountLoginRequestDTO
 */
export interface AccountLoginRequestDTO {
    /**
     *
     */
    identifier: string;
    /**
     *
     */
    password: string;
}

/**
 * Check if a given object implements the AccountLoginRequestDTO interface.
 */
export function instanceOfAccountLoginRequestDTO(value: object): value is AccountLoginRequestDTO {
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AccountLoginRequestDTOFromJSON(json: any): AccountLoginRequestDTO {
    return AccountLoginRequestDTOFromJSONTyped(json, false);
}

export function AccountLoginRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountLoginRequestDTO {
    if (json == null) {
        return json;
    }
    return {

        'identifier': json['identifier'],
        'password': json['password'],
    };
}

export function AccountLoginRequestDTOToJSON(json: any): AccountLoginRequestDTO {
    return AccountLoginRequestDTOToJSONTyped(json, false);
}

export function AccountLoginRequestDTOToJSONTyped(value?: AccountLoginRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'identifier': value['identifier'],
        'password': value['password'],
    };
}
