/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AccountResetPasswordRequestDTO
 */
export interface AccountResetPasswordRequestDTO {
    /**
     *
     */
    token: string;
    /**
     *
     */
    password: string;
}

/**
 * Check if a given object implements the AccountResetPasswordRequestDTO interface.
 */
export function instanceOfAccountResetPasswordRequestDTO(value: object): value is AccountResetPasswordRequestDTO {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AccountResetPasswordRequestDTOFromJSON(json: any): AccountResetPasswordRequestDTO {
    return AccountResetPasswordRequestDTOFromJSONTyped(json, false);
}

export function AccountResetPasswordRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResetPasswordRequestDTO {
    if (json == null) {
        return json;
    }
    return {

        'token': json['token'],
        'password': json['password'],
    };
}

export function AccountResetPasswordRequestDTOToJSON(json: any): AccountResetPasswordRequestDTO {
    return AccountResetPasswordRequestDTOToJSONTyped(json, false);
}

export function AccountResetPasswordRequestDTOToJSONTyped(value?: AccountResetPasswordRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'token': value['token'],
        'password': value['password'],
    };
}
