/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AccountVerifyEmailRequestDTO
 */
export interface AccountVerifyEmailRequestDTO {
    /**
     *
     */
    token: string;
}

/**
 * Check if a given object implements the AccountVerifyEmailRequestDTO interface.
 */
export function instanceOfAccountVerifyEmailRequestDTO(value: object): value is AccountVerifyEmailRequestDTO {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AccountVerifyEmailRequestDTOFromJSON(json: any): AccountVerifyEmailRequestDTO {
    return AccountVerifyEmailRequestDTOFromJSONTyped(json, false);
}

export function AccountVerifyEmailRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountVerifyEmailRequestDTO {
    if (json == null) {
        return json;
    }
    return {

        'token': json['token'],
    };
}

export function AccountVerifyEmailRequestDTOToJSON(json: any): AccountVerifyEmailRequestDTO {
    return AccountVerifyEmailRequestDTOToJSONTyped(json, false);
}

export function AccountVerifyEmailRequestDTOToJSONTyped(value?: AccountVerifyEmailRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'token': value['token'],
    };
}
