/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';

/**
 *
 * @export
 * @interface AccountRegisterResponseDTO
 */
export interface AccountRegisterResponseDTO {
    /**
     *
     */
    account?: Account;
}

/**
 * Check if a given object implements the AccountRegisterResponseDTO interface.
 */
export function instanceOfAccountRegisterResponseDTO(value: object): value is AccountRegisterResponseDTO {
    return true;
}

export function AccountRegisterResponseDTOFromJSON(json: any): AccountRegisterResponseDTO {
    return AccountRegisterResponseDTOFromJSONTyped(json, false);
}

export function AccountRegisterResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRegisterResponseDTO {
    if (json == null) {
        return json;
    }
    return {

        'account': json['account'] == null ? undefined : AccountFromJSON(json['account']),
    };
}

export function AccountRegisterResponseDTOToJSON(json: any): AccountRegisterResponseDTO {
    return AccountRegisterResponseDTOToJSONTyped(json, false);
}

export function AccountRegisterResponseDTOToJSONTyped(value?: AccountRegisterResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'account': AccountToJSON(value['account']),
    };
}
