/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AccountChangePasswordRequestDTO
 */
export interface AccountChangePasswordRequestDTO {
    /**
     *
     */
    currentPassword: string;
    /**
     *
     */
    newPassword: string;
}

/**
 * Check if a given object implements the AccountChangePasswordRequestDTO interface.
 */
export function instanceOfAccountChangePasswordRequestDTO(value: object): value is AccountChangePasswordRequestDTO {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function AccountChangePasswordRequestDTOFromJSON(json: any): AccountChangePasswordRequestDTO {
    return AccountChangePasswordRequestDTOFromJSONTyped(json, false);
}

export function AccountChangePasswordRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountChangePasswordRequestDTO {
    if (json == null) {
        return json;
    }
    return {

        'currentPassword': json['currentPassword'],
        'newPassword': json['newPassword'],
    };
}

export function AccountChangePasswordRequestDTOToJSON(json: any): AccountChangePasswordRequestDTO {
    return AccountChangePasswordRequestDTOToJSONTyped(json, false);
}

export function AccountChangePasswordRequestDTOToJSONTyped(value?: AccountChangePasswordRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'currentPassword': value['currentPassword'],
        'newPassword': value['newPassword'],
    };
}
