/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MinimumVersions
 */
export interface MinimumVersions {
    /**
     *
     */
    android?: string;
    /**
     *
     */
    ios?: string;
    /**
     *
     */
    desktop?: string;
    /**
     *
     */
    backoffice?: string;
}

/**
 * Check if a given object implements the MinimumVersions interface.
 */
export function instanceOfMinimumVersions(value: object): value is MinimumVersions {
    return true;
}

export function MinimumVersionsFromJSON(json: any): MinimumVersions {
    return MinimumVersionsFromJSONTyped(json, false);
}

export function MinimumVersionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinimumVersions {
    if (json == null) {
        return json;
    }
    return {

        'android': json['android'] == null ? undefined : json['android'],
        'ios': json['ios'] == null ? undefined : json['ios'],
        'desktop': json['desktop'] == null ? undefined : json['desktop'],
        'backoffice': json['backoffice'] == null ? undefined : json['backoffice'],
    };
}

export function MinimumVersionsToJSON(json: any): MinimumVersions {
    return MinimumVersionsToJSONTyped(json, false);
}

export function MinimumVersionsToJSONTyped(value?: MinimumVersions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'android': value['android'],
        'ios': value['ios'],
        'desktop': value['desktop'],
        'backoffice': value['backoffice'],
    };
}
