/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface Tokens
 */
export interface Tokens {
    /**
     *
     */
    type?: string;
    /**
     *
     */
    accessToken?: string;
    /**
     *
     */
    accessTokenExpiresAt?: Date;
    /**
     *
     */
    refreshToken?: string;
    /**
     *
     */
    refreshTokenExpiresAt?: Date;
}

/**
 * Check if a given object implements the Tokens interface.
 */
export function instanceOfTokens(value: object): value is Tokens {
    return true;
}

export function TokensFromJSON(json: any): Tokens {
    return TokensFromJSONTyped(json, false);
}

export function TokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tokens {
    if (json == null) {
        return json;
    }
    return {

        'type': json['type'] == null ? undefined : json['type'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'accessTokenExpiresAt': json['accessTokenExpiresAt'] == null ? undefined : (parseDateTime(json['accessTokenExpiresAt'])),
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'refreshTokenExpiresAt': json['refreshTokenExpiresAt'] == null ? undefined : (parseDateTime(json['refreshTokenExpiresAt'])),
    };
}

export function TokensToJSON(json: any): Tokens {
    return TokensToJSONTyped(json, false);
}

export function TokensToJSONTyped(value?: Tokens | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'type': value['type'],
        'accessToken': value['accessToken'],
        'accessTokenExpiresAt': value['accessTokenExpiresAt'] == null ? value['accessTokenExpiresAt'] : serializeDateTime(value['accessTokenExpiresAt']),
        'refreshToken': value['refreshToken'],
        'refreshTokenExpiresAt': value['refreshTokenExpiresAt'] == null ? value['refreshTokenExpiresAt'] : serializeDateTime(value['refreshTokenExpiresAt']),
    };
}
