/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AccountChangePasswordRequestDTO,
    AccountChangePasswordRequestDTOFromJSON,
    AccountChangePasswordRequestDTOToJSON,
} from '../models/AccountChangePasswordRequestDTO';
import {
    type AccountForgotPasswordRequestDTO,
    AccountForgotPasswordRequestDTOFromJSON,
    AccountForgotPasswordRequestDTOToJSON,
} from '../models/AccountForgotPasswordRequestDTO';
import {
    type AccountLoginRequestDTO,
    AccountLoginRequestDTOFromJSON,
    AccountLoginRequestDTOToJSON,
} from '../models/AccountLoginRequestDTO';
import {
    type AccountLoginResponseDTO,
    AccountLoginResponseDTOFromJSON,
    AccountLoginResponseDTOToJSON,
} from '../models/AccountLoginResponseDTO';
import {
    type AccountMeResponseDTO,
    AccountMeResponseDTOFromJSON,
    AccountMeResponseDTOToJSON,
} from '../models/AccountMeResponseDTO';
import {
    type AccountRefreshRequestDTO,
    AccountRefreshRequestDTOFromJSON,
    AccountRefreshRequestDTOToJSON,
} from '../models/AccountRefreshRequestDTO';
import {
    type AccountRefreshResponseDTO,
    AccountRefreshResponseDTOFromJSON,
    AccountRefreshResponseDTOToJSON,
} from '../models/AccountRefreshResponseDTO';
import {
    type AccountRegisterRequestDTO,
    AccountRegisterRequestDTOFromJSON,
    AccountRegisterRequestDTOToJSON,
} from '../models/AccountRegisterRequestDTO';
import {
    type AccountRegisterResponseDTO,
    AccountRegisterResponseDTOFromJSON,
    AccountRegisterResponseDTOToJSON,
} from '../models/AccountRegisterResponseDTO';
import {
    type AccountResetPasswordRequestDTO,
    AccountResetPasswordRequestDTOFromJSON,
    AccountResetPasswordRequestDTOToJSON,
} from '../models/AccountResetPasswordRequestDTO';
import {
    type AccountVerifyEmailRequestDTO,
    AccountVerifyEmailRequestDTOFromJSON,
    AccountVerifyEmailRequestDTOToJSON,
} from '../models/AccountVerifyEmailRequestDTO';
import {
    type AccountVerifyEmailResponseDTO,
    AccountVerifyEmailResponseDTOFromJSON,
    AccountVerifyEmailResponseDTOToJSON,
} from '../models/AccountVerifyEmailResponseDTO';

export interface ChangePasswordRequest {
    /**
     *
     */
    accountChangePasswordRequestDTO: AccountChangePasswordRequestDTO;
}

export interface ForgotPasswordRequest {
    /**
     *
     */
    accountForgotPasswordRequestDTO: AccountForgotPasswordRequestDTO;
}

export interface LoginRequest {
    /**
     *
     */
    accountLoginRequestDTO: AccountLoginRequestDTO;
}

export interface RefreshRequest {
    /**
     *
     */
    accountRefreshRequestDTO: AccountRefreshRequestDTO;
}

export interface RegisterRequest {
    /**
     *
     */
    accountRegisterRequestDTO: AccountRegisterRequestDTO;
}

export interface ResetPasswordRequest {
    /**
     *
     */
    accountResetPasswordRequestDTO: AccountResetPasswordRequestDTO;
}

export interface VerifyEmailRequest {
    /**
     *
     */
    accountVerifyEmailRequestDTO: AccountVerifyEmailRequestDTO;
}

/**
 *
 */
export class AccountControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for changePassword without sending the request
     */
    async changePasswordRequestOpts(requestParameters: ChangePasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountChangePasswordRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'accountChangePasswordRequestDTO',
                'Required parameter "accountChangePasswordRequestDTO" was null or undefined when calling changePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/accounts/change-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountChangePasswordRequestDTOToJSON(requestParameters['accountChangePasswordRequestDTO']),
        };
    }

    /**
     */
    async changePasswordRaw(requestParameters: ChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.changePasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async changePassword(requestParameters: ChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.changePasswordRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for forgotPassword without sending the request
     */
    async forgotPasswordRequestOpts(requestParameters: ForgotPasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountForgotPasswordRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'accountForgotPasswordRequestDTO',
                'Required parameter "accountForgotPasswordRequestDTO" was null or undefined when calling forgotPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/forgot-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountForgotPasswordRequestDTOToJSON(requestParameters['accountForgotPasswordRequestDTO']),
        };
    }

    /**
     */
    async forgotPasswordRaw(requestParameters: ForgotPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.forgotPasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async forgotPassword(requestParameters: ForgotPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.forgotPasswordRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for login without sending the request
     */
    async loginRequestOpts(requestParameters: LoginRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountLoginRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'accountLoginRequestDTO',
                'Required parameter "accountLoginRequestDTO" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountLoginRequestDTOToJSON(requestParameters['accountLoginRequestDTO']),
        };
    }

    /**
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountLoginResponseDTO>> {
        const requestOptions = await this.loginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountLoginResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountLoginResponseDTO> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logout without sending the request
     */
    async logoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/accounts/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.logoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.logoutRaw(initOverrides);
    }

    /**
     * Creates request options for me without sending the request
     */
    async meRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/accounts/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async meRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountMeResponseDTO>> {
        const requestOptions = await this.meRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountMeResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async me(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountMeResponseDTO> {
        const response = await this.meRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refresh without sending the request
     */
    async refreshRequestOpts(requestParameters: RefreshRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountRefreshRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'accountRefreshRequestDTO',
                'Required parameter "accountRefreshRequestDTO" was null or undefined when calling refresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountRefreshRequestDTOToJSON(requestParameters['accountRefreshRequestDTO']),
        };
    }

    /**
     */
    async refreshRaw(requestParameters: RefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountRefreshResponseDTO>> {
        const requestOptions = await this.refreshRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountRefreshResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async refresh(requestParameters: RefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountRefreshResponseDTO> {
        const response = await this.refreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for register without sending the request
     */
    async registerRequestOpts(requestParameters: RegisterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountRegisterRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'accountRegisterRequestDTO',
                'Required parameter "accountRegisterRequestDTO" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountRegisterRequestDTOToJSON(requestParameters['accountRegisterRequestDTO']),
        };
    }

    /**
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountRegisterResponseDTO>> {
        const requestOptions = await this.registerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountRegisterResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountRegisterResponseDTO> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resetPassword without sending the request
     */
    async resetPasswordRequestOpts(requestParameters: ResetPasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountResetPasswordRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'accountResetPasswordRequestDTO',
                'Required parameter "accountResetPasswordRequestDTO" was null or undefined when calling resetPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/reset-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountResetPasswordRequestDTOToJSON(requestParameters['accountResetPasswordRequestDTO']),
        };
    }

    /**
     */
    async resetPasswordRaw(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.resetPasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async resetPassword(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.resetPasswordRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for verifyEmail without sending the request
     */
    async verifyEmailRequestOpts(requestParameters: VerifyEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountVerifyEmailRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'accountVerifyEmailRequestDTO',
                'Required parameter "accountVerifyEmailRequestDTO" was null or undefined when calling verifyEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/accounts/verify-email`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountVerifyEmailRequestDTOToJSON(requestParameters['accountVerifyEmailRequestDTO']),
        };
    }

    /**
     */
    async verifyEmailRaw(requestParameters: VerifyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountVerifyEmailResponseDTO>> {
        const requestOptions = await this.verifyEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountVerifyEmailResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async verifyEmail(requestParameters: VerifyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountVerifyEmailResponseDTO> {
        const response = await this.verifyEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
