/* tslint:disable */
/* eslint-disable */
/**
 * OnlyFit API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type SystemStatusGetResponseDTO,
    SystemStatusGetResponseDTOFromJSON,
    SystemStatusGetResponseDTOToJSON,
} from '../models/SystemStatusGetResponseDTO';

/**
 *
 */
export class PlatformApi extends runtime.BaseAPI {

    /**
     * Creates request options for platformGetSystemStatus without sending the request
     */
    async platformGetSystemStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/system/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get public platform status
     */
    async platformGetSystemStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemStatusGetResponseDTO>> {
        const requestOptions = await this.platformGetSystemStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemStatusGetResponseDTOFromJSON(jsonValue));
    }

    /**
     * Get public platform status
     */
    async platformGetSystemStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemStatusGetResponseDTO> {
        const response = await this.platformGetSystemStatusRaw(initOverrides);
        return await response.value();
    }

}
